
import streamlit as st
import pandas as pd
import numpy as np
import json
import joblib
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import plotly.express as px
import plotly.graph_objects as go
from io import StringIO

# ---------------------------- Page Config ----------------------------
st.set_page_config(page_title="TacticalFitAI – Advanced Demo", layout="wide")

# ---------------------------- Header ----------------------------
st.title("⚽ TacticalFitAI – Advanced Demo (All Positions)")
st.caption("Data-driven recruitment tool • Cosine Similarity + Adjustable Weights • Streamlit Demo")

st.markdown("""
This demo ranks **all 11 positions** by how well they fit a tactical system.
It combines a **Weighted FitScore** with a **Cosine Similarity** score to an **Ideal Tactical Profile**, then blends them into an **Overall Score**.
""")

# ---------------------------- Load Data & Profiles ----------------------------
@st.cache_data(ttl=60)
def load_players():
    paths = ["data/players_fm.csv", "players_fm.csv"]
    for p in paths:
        try:
            df = pd.read_csv(p, encoding="utf-8")
            return df
        except Exception:
            continue
    st.error("⚠️ Could not find `data/players_fm.csv`. Run `fm_data_pipeline.py` first.")
    return None

@st.cache_resource
def load_role_classifier():
    """Load trained XGBoost role classifier (models/role_classifier.pkl)"""
    try:
        bundle = joblib.load("models/role_classifier.pkl")
        return bundle
    except FileNotFoundError:
        return None

@st.cache_data(ttl=300)
def load_role_classifier_report():
    """Load role classifier report (SHAP, metrics) from JSON"""
    try:
        with open("models/role_classifier_report.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

@st.cache_data(ttl=300)
def load_role_profiles():
    """Load data-driven role profiles from JSON (generated by role_profiler.py)"""
    try:
        with open("data/role_profiles.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        st.warning("⚠️ role_profiles.json not found. Run `role_profiler.py` first.")
        return {}

df = load_players()
ROLE_PROFILES = load_role_profiles()
CLASSIFIER_BUNDLE = load_role_classifier()
CLASSIFIER_REPORT = load_role_classifier_report()

if df is None:
    st.stop()

# FM attributes used throughout the app
ATTR_COLS = [
    "Finishing", "Positioning", "Speed", "Strength", "Passing", "Vision",
    "Aggression", "Composure", "OffTheBall", "WorkRate", "Tackling",
    "Marking", "Heading", "Dribbling", "Technique"
]

# Ensure all attribute columns exist and are numeric
for col in ATTR_COLS:
    if col not in df.columns:
        df[col] = 10.0
    df[col] = pd.to_numeric(df[col], errors="coerce").fillna(10.0).clip(1, 20)

# Ensure meta columns
if "MarketValue" not in df.columns:
    df["MarketValue"] = 5.0
if "Best Role" not in df.columns:
    df["Best Role"] = "Unknown"
if "Division" not in df.columns:
    df["Division"] = "Unknown"
if "Club" not in df.columns:
    df["Club"] = "Unknown"

# ---------------------------- Sidebar Controls ----------------------------
st.sidebar.header("🧠 Tactical Settings")

system = st.sidebar.selectbox("Tactical System", ["3-4-2-1", "4-3-3"], index=0)

# Position Selection
position = st.sidebar.selectbox("Position", ["GK", "CB", "RB", "LB", "CDM", "CM", "CAM", "RW", "LW", "ST"], index=9)

# Dynamic role selection based on position
role_options = {
    "GK":  ["Goalkeeper", "Sweeper Keeper"],
    "CB":  ["Central Defender", "Ball Playing Defender", "No-Nonsense CB"],
    "RB":  ["Full Back", "Wing Back", "Complete Wing Back", "Inverted Wing Back"],
    "LB":  ["Full Back", "Wing Back", "Complete Wing Back", "Inverted Wing Back"],
    "CDM": ["Ball Winning Midfielder", "Defensive Midfielder", "Deep Lying Playmaker", "Anchor"],
    "CM":  ["Central Midfielder", "Box to Box", "Mezzala", "Carrilero"],
    "CAM": ["Advanced Playmaker", "Shadow Striker", "Enganche", "Trequartista", "Mezzala"],
    "RW":  ["Winger", "Inverted Winger", "Defensive Winger"],
    "LW":  ["Winger", "Inverted Winger", "Defensive Winger"],
    "ST":  ["Poacher", "Advanced Forward", "Target Man", "Deep Lying Forward", "Pressing Forward", "Inside Forward", "False Nine"]
}

player_role = st.sidebar.selectbox("Player Role", role_options[position], index=0)

st.sidebar.subheader("⚙️ Attribute Weights")
w_fin = st.sidebar.slider("Finishing",    0.0, 1.0, 0.20, 0.01)
w_pos = st.sidebar.slider("Positioning",  0.0, 1.0, 0.15, 0.01)
w_spd = st.sidebar.slider("Speed",        0.0, 1.0, 0.10, 0.01)
w_str = st.sidebar.slider("Strength",     0.0, 1.0, 0.08, 0.01)
w_pas = st.sidebar.slider("Passing",      0.0, 1.0, 0.12, 0.01)
w_vis = st.sidebar.slider("Vision",       0.0, 1.0, 0.10, 0.01)
w_agg = st.sidebar.slider("Aggression",   0.0, 1.0, 0.05, 0.01)
w_com = st.sidebar.slider("Composure",    0.0, 1.0, 0.07, 0.01)
w_otb = st.sidebar.slider("OffTheBall",   0.0, 1.0, 0.08, 0.01)
w_wor = st.sidebar.slider("WorkRate",     0.0, 1.0, 0.05, 0.01)
w_tck = st.sidebar.slider("Tackling",     0.0, 1.0, 0.05, 0.01)
w_mar = st.sidebar.slider("Marking",      0.0, 1.0, 0.05, 0.01)
w_hea = st.sidebar.slider("Heading",      0.0, 1.0, 0.03, 0.01)
w_dri = st.sidebar.slider("Dribbling",    0.0, 1.0, 0.03, 0.01)
w_tec = st.sidebar.slider("Technique",    0.0, 1.0, 0.03, 0.01)

normalize_weights = st.sidebar.checkbox("Normalize weights to sum=1", value=True, help="If on, weights will be proportionally normalized.")
use_minmax = st.sidebar.checkbox("Normalize attributes (Min-Max) before scoring", value=True, help="Makes different scales comparable.")

alpha = st.sidebar.slider("Blend: FitScore vs Cosine Similarity", 0.0, 1.0, 0.7, 0.05, help="Overall = alpha*FitScore + (1-alpha)*SimilarityScore")

top_n = st.sidebar.slider("Show Top N", 5, 20, 10, 1)
show_balloons = st.sidebar.checkbox("Celebrate after analysis 🎈", value=False)

st.sidebar.markdown("---")
st.sidebar.subheader("🌍 Player Pool Filter")

# League filter
all_divisions = sorted(df["Division"].dropna().unique().tolist())
selected_leagues = st.sidebar.multiselect(
    "Leagues (ไม่เลือก = ทุกลีก)",
    options=all_divisions,
    default=[],
    help="เลือกลีกที่ต้องการขอบเขต — ว่างไว้ = ใช้ทุกลีก"
)

# Age filter
min_age = int(df["Age"].min()) if "Age" in df.columns else 15
max_age = int(df["Age"].max()) if "Age" in df.columns else 40
age_range = st.sidebar.slider(
    "Age Range",
    min_value=min_age,
    max_value=max_age,
    value=(min_age, max_age),
    step=1
)

# Min Market Value filter (€M)
mv_min = st.sidebar.number_input(
    "Min Market Value (€M)",
    min_value=0.0,
    max_value=50.0,
    value=0.0,
    step=0.5,
    help="กรอง: เฉพาะนักเตะที่ Market Value ≥ ค่านี้"
)

# ---------------------------- Weight Handling ----------------------------
weights = {
    "Finishing":   w_fin,
    "Positioning": w_pos,
    "Speed":       w_spd,
    "Strength":    w_str,
    "Passing":     w_pas,
    "Vision":      w_vis,
    "Aggression":  w_agg,
    "Composure":   w_com,
    "OffTheBall":  w_otb,
    "WorkRate":    w_wor,
    "Tackling":    w_tck,
    "Marking":     w_mar,
    "Heading":     w_hea,
    "Dribbling":   w_dri,
    "Technique":   w_tec,
}

# Normalize weights if needed
if normalize_weights:
    total = sum(weights.values()) or 1.0
    weights = {k: v/total for k, v in weights.items()}

# ---------------------------- Apply Filters ----------------------------
df_filtered = df.copy()

if selected_leagues:
    df_filtered = df_filtered[df_filtered["Division"].isin(selected_leagues)]

if "Age" in df_filtered.columns:
    df_filtered["Age"] = pd.to_numeric(df_filtered["Age"], errors="coerce")
    df_filtered = df_filtered[
        (df_filtered["Age"] >= age_range[0]) &
        (df_filtered["Age"] <= age_range[1])
    ]

df_filtered = df_filtered[df_filtered["MarketValue"] >= mv_min]

# Filter by position
df_pos = df_filtered[df_filtered["Position"] == position].copy()

# Show player count in sidebar
st.sidebar.markdown(f"""
---
**👥 Player Pool:**  
`{len(df_filtered):,}` total | `{len(df_pos):,}` as {position}
""")

if len(df_pos) == 0:
    st.warning(f"⚠️ ไม่มีนักเตะ {position} ที่ตรงกับ filter ที่เลือก กรุณาปรับเงื่อนไข")
    st.stop()

def minmax(series):
    smin, smax = series.min(), series.max()
    if smax == smin:
        return pd.Series([0.0]*len(series), index=series.index)
    return (series - smin) / (smax - smin)

def generate_explanation(row, system: str, weights: dict, top_n: int = 3):
    """Generate explanation for why a player fits the tactical system"""
    all_attrs = {a: row.get(a, 0) for a in ATTR_COLS}

    # Weight contribution for each attribute
    contributions = {}
    for attr, value in all_attrs.items():
        if weights.get(attr, 0) > 0:
            contributions[attr] = value * weights[attr]

    # Sort by contribution
    top_attrs = sorted(contributions.items(), key=lambda x: x[1], reverse=True)[:top_n]

    # Generate explanation text
    explanations = []
    for attr, contrib in top_attrs:
        value = all_attrs[attr]
        if value >= 18:
            level = "Exceptional"
        elif value >= 16:
            level = "Excellent"
        elif value >= 14:
            level = "Very Good"
        elif value >= 12:
            level = "Good"
        else:
            level = "Adequate"
        explanations.append(f"{attr}: {level} ({int(value)}/20)")

    return " • ".join(explanations)

# ---------------------------- ML: Player Similarity ----------------------------
@st.cache_data
def compute_similarity_matrix(df_src: pd.DataFrame):
    """Compute player similarity matrix using FM attributes"""
    feature_cols = ATTR_COLS  # use the global FM attribute list
    available = [c for c in feature_cols if c in df_src.columns]

    X = df_src[available].values
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    similarity_matrix = cosine_similarity(X_scaled)

    return similarity_matrix

def find_similar_players(df_src: pd.DataFrame, player_name: str, similarity_matrix, top_n=5, min_score=0.75):
    """Find similar players using ML"""
    try:
        player_idx = df_src[df_src['Player'] == player_name].index[0]
    except IndexError:
        return None

    scores = similarity_matrix[player_idx]

    results = pd.DataFrame({
        'Player': df_src['Player'],
        'Position': df_src['Position'],
        'Similarity': scores * 100,
        'MarketValue': df_src['MarketValue'],
        'OverallScore': df_src.get('OverallScore', 0)
    })

    results = results[results['Player'] != player_name]
    results = results[results['Similarity'] >= min_score * 100]
    results = results.sort_values('Similarity', ascending=False)

    return results.head(top_n)

def get_role_profile(role: str):
    """Load ideal attribute profile from data/role_profiles.json (data-driven centroids)"""
    if role in ROLE_PROFILES:
        p = ROLE_PROFILES[role]
        ideal_dict = p["ideal"]
        # Build numpy array matching ATTR_COLS order
        ideal_vec = np.array([[ideal_dict.get(a, 10.0) for a in ATTR_COLS]])
        return {
            "description": f"{role} — {p.get('dominant_position','?')} (n={p.get('n_players',0):,})",
            "ideal": ideal_vec,
            "key_attrs": p.get("key_attrs", ATTR_COLS[:4])
        }
    # Fallback: average of all players (scale 1-20, midpoint = 10)
    fallback = np.array([[10.0] * len(ATTR_COLS)])
    return {"description": f"{role} (fallback)", "ideal": fallback, "key_attrs": ATTR_COLS[:4]}

def compute_scores(df_src: pd.DataFrame, system: str, role: str, weights: dict, use_minmax: bool, alpha: float):
    df_calc = df_src.copy()

    # Get role-specific profile (data-driven from role_profiles.json)
    role_profile = get_role_profile(role)
    ideal = role_profile["ideal"].astype(float)  # shape (1, len(ATTR_COLS))

    # Tactical system adjustment — small multipliers per formation
    # Order matches ATTR_COLS: Fin, Pos, Spd, Str, Pas, Vis, Agg, Cmp, OTB, Wor, Tck, Mar, Hea, Dri, Tec
    if system == "3-4-2-1":
        mults = np.array([[1.0, 1.05, 1.0, 1.0, 0.98, 1.0, 1.02, 1.0, 1.03, 1.02, 1.0, 1.0, 1.0, 1.0, 1.0]])
    elif system == "4-3-3":
        mults = np.array([[1.0, 1.03, 1.05, 0.98, 1.0, 1.0, 1.0, 1.0, 1.02, 1.0, 1.0, 1.0, 1.0, 1.02, 1.0]])
    else:
        mults = np.ones((1, len(ATTR_COLS)))

    ideal = np.clip(ideal * mults, 1, 20)

    # Build player attribute matrix
    df_attrs = df_calc[ATTR_COLS].copy()

    # Optional MinMax normalize
    if use_minmax:
        for c in ATTR_COLS:
            mn, mx = df_attrs[c].min(), df_attrs[c].max()
            if mx > mn:
                df_attrs[c] = (df_attrs[c] - mn) / (mx - mn) * 20

    # Weighted FitScore — use weights for matching attrs, default 0 for others
    df_calc["FitScore"] = sum(
        df_attrs[a] * weights.get(a, 0.0)
        for a in ATTR_COLS if a in df_attrs.columns
    )

    # Cosine Similarity vs ideal vector
    player_vectors = df_attrs.values          # (n, 15)
    sim = cosine_similarity(player_vectors, ideal)
    df_calc["SimilarityScore"] = (sim * 100).round(2)

    # Blend FitScore + SimilarityScore
    df_calc["OverallScore"] = (alpha * df_calc["FitScore"]) + ((1 - alpha) * df_calc["SimilarityScore"])

    # Value for Money
    df_calc["ValueForMoney"] = (df_calc["OverallScore"] / df_calc["MarketValue"].clip(lower=0.1)).round(2)

    # Generate explanations
    df_calc["Explanation"] = df_calc.apply(lambda row: generate_explanation(row, system, weights), axis=1)

    # Round for display
    for c in ["FitScore","OverallScore"]:
        df_calc[c] = df_calc[c].round(2)

    # Sort
    df_calc = df_calc.sort_values("OverallScore", ascending=False)
    return df_calc

# Filter by search only (position already applied via df_pos)
with st.container():
    search = st.text_input("🔍 Search player", placeholder="Type a player name…")
    base_df = df_pos.copy()

    if search:
        base_df = base_df[base_df["Player"].str.contains(search, case=False, na=False)]

# Check if we have any players after filtering
if len(base_df) == 0:
    st.error(f"❌ No players found for position '{position}' with current filters")
    st.info(f"Available positions in dataset: {', '.join(sorted(df_filtered['Position'].unique()))}")
    st.stop()

ranked = compute_scores(base_df, system, player_role, weights, use_minmax, alpha)

if show_balloons:
    st.balloons()

# ---------------------------- Compute ML Similarity Matrix ----------------------------
similarity_matrix = compute_similarity_matrix(df_filtered)

# ---------------------------- Tabs Layout ----------------------------
tab1, tab2, tab3, tab4, tab5, tab6 = st.tabs(["🏆 Ranking", "📊 Head-to-Head", "📈 Radar Chart", "🤖 Player Similarity (ML)", "⚙️ Settings & Export", "🎓 Role Classifier (ML)"])

with tab1:
    role_info = get_role_profile(player_role)
    st.info(f"**{player_role}**: {role_info['description']}")

    position_display = {
        "GK": "Goalkeepers",
        "CB": "Center Backs",
        "RB": "Right Backs",
        "LB": "Left Backs",
        "CDM": "Defensive Midfielders",
        "CM": "Central Midfielders",
        "CAM": "Attacking Midfielders",
        "RW": "Right Wingers",
        "LW": "Left Wingers",
        "ST": "Strikers"
    }

    st.subheader(f"Top {top_n} {position_display[position]} – Overall Score ({system} | {player_role})")

    # Display table with market value
    display_cols = ["Player","FitScore","SimilarityScore","OverallScore","MarketValue","ValueForMoney","Explanation"]
    ranked_display = ranked[display_cols].head(top_n).copy()
    ranked_display['MarketValue'] = ranked_display['MarketValue'].apply(lambda x: f"€{x:.1f}M")
    st.dataframe(ranked_display.reset_index(drop=True), use_container_width=True)

    # Add best value option
    st.markdown("---")
    st.markdown("### 💎 Best Value Picks")
    st.caption("Players offering the best performance per euro spent")

    # Show top 5 value for money
    value_picks = ranked.nlargest(5, 'ValueForMoney')[['Player', 'OverallScore', 'MarketValue', 'ValueForMoney']].copy()
    value_picks['MarketValue'] = value_picks['MarketValue'].apply(lambda x: f"€{x:.1f}M")

    cols = st.columns(5)
    for idx, (_, player) in enumerate(value_picks.iterrows()):
        with cols[idx]:
            st.metric(
                label=player['Player'],
                value=f"{player['OverallScore']:.1f}",
                delta=f"€{player['MarketValue']}"
            )
            st.caption(f"Value: {player['ValueForMoney']:.2f}")

    fig = px.bar(
        ranked.head(top_n),
        x="Player",
        y="OverallScore",
        color="OverallScore",
        color_continuous_scale="RdYlGn",
        title=f"Overall Score (Blend α={alpha:.2f}) – Top {top_n}"
    )
    st.plotly_chart(fig, use_container_width=True)

    # Show detailed explanation for top 3
    st.markdown("---")
    st.subheader("💡 Why These Players Fit")
    for idx, row in ranked.head(3).iterrows():
        with st.expander(f"**{row['Player']}** - Overall Score: {row['OverallScore']:.2f}"):
            st.write(f"**Tactical Fit Explanation:**")
            st.info(row['Explanation'])
            st.write(f"**Key Stats:**")
            cols = st.columns(4)
            cols[0].metric("FitScore", f"{row['FitScore']:.2f}")
            cols[1].metric("Similarity", f"{row['SimilarityScore']:.2f}")
            cols[2].metric("Work Rate", f"{row.get('WorkRate', 0):.1f}")
            cols[3].metric("Market Value", f"€{row['MarketValue']:.1f}M")

with tab2:
    st.subheader("📊 Head-to-Head Player Comparison")
    st.markdown("Compare multiple players side-by-side with detailed statistics")

    # Player selection
    candidates = ranked["Player"].head(max(20, top_n)).tolist()
    chosen = st.multiselect("Select players to compare (2-5 recommended):", candidates, default=candidates[:3])

    if len(chosen) >= 2:
        comparison_df = ranked[ranked["Player"].isin(chosen)].copy()

        # Core attributes for comparison (FM attributes)
        all_attrs = ["Finishing", "Positioning", "Speed", "Strength", "Passing",
                     "Vision", "Aggression", "Composure", "OffTheBall", "WorkRate", "Tackling", "Technique"]

        # Display scores first
        st.markdown("### 🎯 Overall Scores")
        score_cols = st.columns(len(chosen))
        for idx, player in enumerate(chosen):
            player_data = comparison_df[comparison_df["Player"] == player].iloc[0]
            with score_cols[idx]:
                st.metric(
                    label=player,
                    value=f"{player_data['OverallScore']:.2f}",
                    delta=None
                )
                st.caption(f"Fit: {player_data['FitScore']:.2f} | Sim: {player_data['SimilarityScore']:.2f}")

        st.markdown("---")

        # Detailed comparison table
        st.markdown("### 📋 Detailed Attributes")

        # Create comparison table
        comparison_table = comparison_df[["Player"] + all_attrs + ["FitScore", "SimilarityScore", "OverallScore"]].copy()

        # Transpose for better readability
        comparison_transposed = comparison_table.set_index("Player").T

        # Style the dataframe
        def highlight_max(s):
            is_max = s == s.max()
            return ['background-color: lightgreen' if v else '' for v in is_max]

        def highlight_min(s):
            is_min = s == s.min()
            return ['background-color: lightcoral' if v else '' for v in is_min]

        styled_table = comparison_transposed.style.apply(highlight_max, axis=1)
        st.dataframe(styled_table, use_container_width=True, height=600)

        st.markdown("---")

        # Side-by-side attribute comparison with bar charts
        st.markdown("### 📊 Visual Comparison")

        # Create bar charts for each attribute group
        col1, col2 = st.columns(2)

        with col1:
            st.markdown("**⚔️ Attacking Attributes**")
            attacking_attrs = ["Finishing", "Positioning", "OffTheBall", "Vision"]
            for attr in attacking_attrs:
                if attr in comparison_table.columns:
                    fig_attr = px.bar(
                        comparison_table,
                        x="Player",
                        y=attr,
                        title=attr,
                        color="Player",
                        text=attr
                    )
                    fig_attr.update_traces(texttemplate='%{text:.0f}', textposition='outside')
                    fig_attr.update_layout(showlegend=False, height=250)
                    st.plotly_chart(fig_attr, use_container_width=True)

        with col2:
            st.markdown("**🛡️ Physical & Defensive Attributes**")
            defensive_attrs = ["Speed", "Strength", "Aggression", "Composure"]
            for attr in defensive_attrs:
                if attr in comparison_table.columns:
                    fig_attr = px.bar(
                        comparison_table,
                        x="Player",
                        y=attr,
                        title=attr,
                        color="Player",
                        text=attr
                    )
                    fig_attr.update_traces(texttemplate='%{text:.0f}', textposition='outside')
                    fig_attr.update_layout(showlegend=False, height=250)
                    st.plotly_chart(fig_attr, use_container_width=True)

        # Advanced stats
        st.markdown("---")
        st.markdown("### 📈 Advanced Statistics & Market Value")
        adv_cols = st.columns(len(chosen))
        for idx, player in enumerate(chosen):
            player_data = comparison_df[comparison_df["Player"] == player].iloc[0]
            with adv_cols[idx]:
                st.markdown(f"**{player}**")
                st.metric("💰 Market Value", f"€{player_data['MarketValue']:.1f}M")
                st.metric("Work Rate", f"{player_data.get('WorkRate', 0):.1f}")
                st.metric("Technique", f"{player_data.get('Technique', 0):.1f}")
                st.metric("Passing", f"{player_data['Passing']:.0f}")

    elif len(chosen) == 1:
        st.warning("⚠️ Please select at least 2 players to compare")
    else:
        st.info("👆 Select players from the dropdown above to start comparing")

with tab3:
    st.subheader("📈 Radar Chart - Attribute Visualization")
    st.markdown("Visual comparison of player attributes using radar charts")

    candidates = ranked["Player"].head(max(10, top_n)).tolist()
    chosen_radar = st.multiselect("Select players for radar chart (2-4 recommended):", candidates, default=candidates[:2], key="radar_select")

    if chosen_radar:
        # All important attributes for radar
        radar_attrs = ["Finishing", "Positioning", "Speed", "Strength", "Passing",
                       "Vision", "Aggression", "Composure", "OffTheBall"]

        fig_radar = go.Figure()

        colors = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A', '#98D8C8']

        for idx, p in enumerate(chosen_radar):
            row = ranked[ranked["Player"] == p][radar_attrs]
            if row.empty:
                continue
            stats = row.values.flatten().tolist()
            stats += stats[:1]  # Close the radar

            fig_radar.add_trace(go.Scatterpolar(
                r=stats,
                theta=radar_attrs + [radar_attrs[0]],
                fill="toself",
                name=p,
                line=dict(color=colors[idx % len(colors)], width=2),
                opacity=0.7
            ))

        fig_radar.update_layout(
            polar=dict(
                radialaxis=dict(
                    visible=True,
                    range=[0, 20],
                    tickfont=dict(size=10)
                )
            ),
            showlegend=True,
            title="Player Attribute Comparison - Radar Chart",
            height=600
        )
        st.plotly_chart(fig_radar, use_container_width=True)

        # Show the exact numbers
        st.markdown("---")
        st.markdown("**📋 Attribute Values**")
        st.dataframe(
            ranked[ranked["Player"].isin(chosen_radar)][["Player"] + radar_attrs + ["FitScore", "SimilarityScore", "OverallScore"]],
            use_container_width=True
        )

        # Add interpretation
        st.markdown("---")
        st.markdown("### 💡 How to Read the Radar Chart")
        st.markdown("""
        - **Larger area** = Better overall attributes
        - **Points further from center** = Higher values in specific attributes
        - **Compare shapes** to see strengths and weaknesses
        - Ideal for identifying player profiles at a glance
        """)
    else:
        st.info("👆 Select at least one player to visualize their attributes")

with tab4:
    st.subheader("🤖 Player Similarity Finder (Machine Learning)")
    st.markdown("Find players with similar playing styles using **Machine Learning algorithms**")

    st.info("💡 **How it works**: Uses StandardScaler + Cosine Similarity on 15 FM attributes (Finishing, Positioning, Speed, Strength, Passing, Vision, Aggression, Composure, OffTheBall, WorkRate, Tackling, Marking, Heading, Dribbling, Technique)")

    # Player selection
    all_players = sorted(df['Player'].tolist())
    selected_player = st.selectbox("Select a player to find similar players:", all_players, index=all_players.index("Kevin De Bruyne") if "Kevin De Bruyne" in all_players else 0)

    col1, col2 = st.columns(2)
    with col1:
        min_similarity = st.slider("Minimum Similarity Score (%)", 50, 95, 75, 5)
    with col2:
        num_results = st.slider("Number of Results", 3, 10, 5)

    # Filter options
    filter_by_position = st.checkbox("Filter by same position only", value=False)

    if st.button("🔍 Find Similar Players", type="primary"):
        # Get selected player info
        selected_info = df[df['Player'] == selected_player].iloc[0]

        # Find similar players
        similar = find_similar_players(df, selected_player, similarity_matrix, top_n=num_results, min_score=min_similarity/100)

        if filter_by_position:
            similar = similar[similar['Position'] == selected_info['Position']]

        if similar is not None and len(similar) > 0:
            st.markdown("---")
            st.markdown(f"### 🎯 Selected Player: **{selected_player}**")

            cols = st.columns(4)
            cols[0].metric("Position", selected_info['Position'])
            cols[1].metric("Market Value", f"€{selected_info['MarketValue']:.1f}M")
            cols[2].metric("Finishing", f"{selected_info['Finishing']:.0f}")
            cols[3].metric("Passing", f"{selected_info['Passing']:.0f}")

            st.markdown("---")
            st.markdown(f"### 📊 Top {len(similar)} Most Similar Players")

            # Display as cards
            for idx, row in similar.iterrows():
                with st.expander(f"**{row['Similarity']:.1f}%** - {row['Player']} ({row['Position']})", expanded=idx==similar.index[0]):
                    col_a, col_b, col_c = st.columns(3)

                    player_data = df[df['Player'] == row['Player']].iloc[0]

                    with col_a:
                        st.metric("Market Value", f"€{row['MarketValue']:.1f}M")
                        st.metric("Position", row['Position'])

                    with col_b:
                        st.metric("Finishing", f"{player_data['Finishing']:.0f}")
                        st.metric("Speed", f"{player_data['Speed']:.0f}")

                    with col_c:
                        st.metric("Passing", f"{player_data['Passing']:.0f}")
                        st.metric("Vision", f"{player_data['Vision']:.0f}")

                    # Mini radar comparison
                    radar_attrs = ["Finishing", "Positioning", "Speed", "Strength", "Passing"]

                    selected_stats = [selected_info[attr] for attr in radar_attrs]
                    similar_stats = [player_data[attr] for attr in radar_attrs]

                    fig_mini = go.Figure()

                    fig_mini.add_trace(go.Scatterpolar(
                        r=selected_stats + [selected_stats[0]],
                        theta=radar_attrs + [radar_attrs[0]],
                        fill='toself',
                        name=selected_player,
                        line=dict(color='#FF6B6B', width=2)
                    ))

                    fig_mini.add_trace(go.Scatterpolar(
                        r=similar_stats + [similar_stats[0]],
                        theta=radar_attrs + [radar_attrs[0]],
                        fill='toself',
                        name=row['Player'],
                        line=dict(color='#4ECDC4', width=2)
                    ))

                    fig_mini.update_layout(
                        polar=dict(radialaxis=dict(visible=True, range=[0, 20])),
                        showlegend=True,
                        height=300
                    )

                    st.plotly_chart(fig_mini, use_container_width=True)
        else:
            st.warning(f"⚠️ No similar players found with similarity >= {min_similarity}%")

    st.markdown("---")
    st.markdown("### 🎓 Technical Details")
    st.markdown("""
    **Algorithm**: Cosine Similarity
    - **Features Used**: 15 FM dimensions (Finishing, Positioning, Speed, Strength, Passing, Vision, Aggression, Composure, OffTheBall, WorkRate, Tackling, Marking, Heading, Dribbling, Technique)
    - **Preprocessing**: StandardScaler (z-score normalization)
    - **Similarity Metric**: Cosine Similarity (measures angle between feature vectors)

    **Use Cases**:
    - 🔄 Find replacement for injured/transferred players
    - 💰 Find cheaper alternatives with similar style
    - 🎯 Scout players with similar profiles from different leagues
    - 📊 Analyze player archetypes and clusters
    """)

with tab5:
    st.subheader("Current Settings")
    st.write(f"**System:** {system}")
    st.write("**Weights (after normalization if enabled):**")
    st.json(weights)
    st.write(f"**Use MinMax Normalization:** {use_minmax}")
    st.write(f"**Blend α (Fit vs Cosine):** {alpha}")

    # Export ranked data
    csv_buf = StringIO()
    ranked.to_csv(csv_buf, index=False)
    st.download_button("📥 Download Ranked Results (CSV)", data=csv_buf.getvalue(), file_name="tacticalfitai_ranked.csv", mime="text/csv")

    # Simple ML (optional): show learned coefficients aligning with current FitScore as target
    st.markdown("---")
    st.subheader("🧪 Optional: Learn Feature Importance (Linear Regression)")
    if st.button("Train lightweight model on current data"):
        features = [c for c in ATTR_COLS if c in ranked.columns]
        X = ranked[features].values
        y = ranked["FitScore"].values  # learn to approximate FitScore
        model = LinearRegression().fit(X, y)
        coefs = pd.Series(model.coef_, index=features).sort_values(ascending=False)
        st.write("**Learned coefficients (relative importance):**")
        st.bar_chart(coefs)

with tab6:
    st.subheader("🎓 Role Classifier — XGBoost ML Model")
    st.markdown(
        "ระบบทำนาย **Tactical Role** ที่เหมาะสมที่สุดของผู้เล่น "
        "จาก FM attributes ด้วยโมเดล **XGBoost** (เทรนจาก FM2023 data ~22K players, 34 roles)"
    )

    if CLASSIFIER_BUNDLE is None:
        st.error("⚠️ ไม่พบ `models/role_classifier.pkl` — รัน `ml_role_classifier.py` ก่อน")
    else:
        model_bundle = CLASSIFIER_BUNDLE
        clf        = model_bundle["model"]
        le         = model_bundle["label_encoder"]
        feat_cols  = model_bundle["feature_cols"]   # 20 FM attributes used for training
        model_name = model_bundle.get("model_name", "XGBoost")
        n_classes  = model_bundle.get("n_classes", len(le.classes_))

        # ── Model info banner ─────────────────────────────────
        col_i1, col_i2, col_i3, col_i4 = st.columns(4)
        cv_acc = CLASSIFIER_REPORT.get(f"{model_name}_CV", {}).get("accuracy_mean", 0)
        cv_std = CLASSIFIER_REPORT.get(f"{model_name}_CV", {}).get("accuracy_std", 0)
        f1_w   = CLASSIFIER_REPORT.get("FinalModel", {}).get("f1_weighted", 0)
        col_i1.metric("Model", model_name)
        col_i2.metric("CV Accuracy", f"{cv_acc*100:.1f}% ± {cv_std*100:.1f}%")
        col_i3.metric("F1 Weighted", f"{f1_w*100:.1f}%")
        col_i4.metric("Roles", f"{n_classes}")

        st.caption(
            "⚠️ Accuracy 62.4% เป็นผลที่สมเหตุสมผล — FM มี 34 roles ที่มี semantic overlap สูง "
            "(เช่น Winger vs Inverted Winger) และ random baseline อยู่ที่ ~3%"
        )

        st.markdown("---")

        # ── Player selector ───────────────────────────────────
        st.markdown("### 🔍 เลือกผู้เล่นที่ต้องการทำนาย Role")

        # ensure feat_cols exist in df; fill missing with 10.0
        for fc in feat_cols:
            if fc not in df.columns:
                df[fc] = 10.0

        all_players_sorted = sorted(df["Player"].dropna().unique().tolist())
        default_idx = all_players_sorted.index("Kevin De Bruyne") if "Kevin De Bruyne" in all_players_sorted else 0
        sel_player = st.selectbox(
            "เลือกผู้เล่น:",
            all_players_sorted,
            index=default_idx,
            key="rc_player_select"
        )

        player_row = df[df["Player"] == sel_player]
        if player_row.empty:
            st.warning("ไม่พบข้อมูลผู้เล่นในชุดข้อมูล")
        else:
            player_row = player_row.iloc[0]

            # Build feature vector — fill missing feat_cols with 10.0
            x_vec = np.array([[float(player_row.get(fc, 10.0)) for fc in feat_cols]])

            # Predict probabilities
            proba = clf.predict_proba(x_vec)[0]          # shape: (n_classes,)
            top3_idx = np.argsort(proba)[::-1][:3]
            top3_roles = [(le.classes_[i], float(proba[i])) for i in top3_idx]
            pred_role  = top3_roles[0][0]

            # ── Player info ───────────────────────────────────
            st.markdown(f"#### ผู้เล่น: **{sel_player}**")
            pi1, pi2, pi3, pi4 = st.columns(4)
            pi1.metric("Position (FM)", str(player_row.get("Position", "?")))
            pi2.metric("Best Role (FM label)", str(player_row.get("Best Role", "?")))
            pi3.metric("ML Predicted Role", pred_role)
            pi4.metric("Market Value", f"€{float(player_row.get('MarketValue', 0)):.1f}M")

            match = player_row.get("Best Role", "") == pred_role
            if match:
                st.success("✅ ML prediction ตรงกับ FM Best Role label")
            else:
                st.info(
                    f"ℹ️ ML predicted **{pred_role}** แต่ FM label คือ **{player_row.get('Best Role', '?')}** "
                    "— อาจเกิดจาก semantic overlap ระหว่าง roles"
                )

            st.markdown("---")

            # ── Top 3 predicted roles ─────────────────────────
            st.markdown("### 🏅 Top 3 Predicted Roles")

            colors_prob = ["#2ecc71", "#3498db", "#e67e22"]
            for rank, (role, prob) in enumerate(top3_roles):
                col_rank, col_bar, col_pct = st.columns([1, 6, 1])
                with col_rank:
                    medal = ["🥇", "🥈", "🥉"][rank]
                    st.markdown(f"### {medal}")
                with col_bar:
                    st.markdown(f"**{role}**")
                    st.progress(prob, text="")
                with col_pct:
                    st.markdown(f"**{prob*100:.1f}%**")

            st.markdown("---")

            # ── Radar: player vs ideal centroid of predicted role ─────
            st.markdown(f"### 📈 Attribute Profile vs Ideal Centroid: *{pred_role}*")

            radar_display_cols = [
                "Finishing", "Positioning", "Speed", "Strength",
                "Passing", "Vision", "Aggression", "Composure", "OffTheBall"
            ]
            # Filter to cols present in feat_cols
            radar_display_cols = [c for c in radar_display_cols if c in feat_cols]

            player_vals = [float(player_row.get(c, 10.0)) for c in radar_display_cols]

            # Get ideal centroid from role_profiles.json
            ideal_vals = None
            if pred_role in ROLE_PROFILES:
                ideal_dict = ROLE_PROFILES[pred_role].get("ideal", {})
                ideal_vals = [float(ideal_dict.get(c, 10.0)) for c in radar_display_cols]

            fig_rc_radar = go.Figure()
            fig_rc_radar.add_trace(go.Scatterpolar(
                r=player_vals + [player_vals[0]],
                theta=radar_display_cols + [radar_display_cols[0]],
                fill="toself",
                name=sel_player,
                line=dict(color="#FF6B6B", width=2),
                opacity=0.75
            ))
            if ideal_vals:
                fig_rc_radar.add_trace(go.Scatterpolar(
                    r=ideal_vals + [ideal_vals[0]],
                    theta=radar_display_cols + [radar_display_cols[0]],
                    fill="toself",
                    name=f"Ideal {pred_role}",
                    line=dict(color="#4ECDC4", width=2, dash="dash"),
                    opacity=0.5
                ))
            fig_rc_radar.update_layout(
                polar=dict(radialaxis=dict(visible=True, range=[0, 20])),
                showlegend=True,
                title=f"{sel_player} vs Ideal {pred_role} (FM 1-20 scale)",
                height=500
            )
            st.plotly_chart(fig_rc_radar, use_container_width=True)

            st.markdown("---")

            # ── SHAP / RF Feature Importance ─────────────────
            st.markdown("### 🔬 Feature Importance (จาก SHAP / RF)")

            shap_data = CLASSIFIER_REPORT.get("SHAP_importance") or CLASSIFIER_REPORT.get("RF_feature_importance", {})
            if shap_data:
                imp_df = pd.DataFrame(
                    list(shap_data.items()),
                    columns=["Attribute", "Importance"]
                ).sort_values("Importance", ascending=False).head(15)

                fig_imp = px.bar(
                    imp_df,
                    x="Importance",
                    y="Attribute",
                    orientation="h",
                    color="Importance",
                    color_continuous_scale="Blues",
                    title="Top 15 Most Important Attributes for Role Classification"
                )
                fig_imp.update_layout(yaxis=dict(autorange="reversed"), height=450)
                st.plotly_chart(fig_imp, use_container_width=True)

                top5 = imp_df.head(5)["Attribute"].tolist()
                st.caption(
                    f"**Top 5 attributes ที่ส่งผลต่อการทำนาย role มากที่สุด:** "
                    + ", ".join(top5)
                )
            else:
                st.info("ไม่พบข้อมูล feature importance ใน report JSON")

            st.markdown("---")

            # ── Full attribute table for selected player ──────
            with st.expander("📋 ดู FM Attributes ครบทุกตัว"):
                attr_display = {fc: round(float(player_row.get(fc, 10.0)), 1) for fc in feat_cols}
                attr_df = pd.DataFrame(
                    list(attr_display.items()), columns=["Attribute", "Value (1-20)"]
                )
                st.dataframe(attr_df, use_container_width=True, hide_index=True)

        st.markdown("---")
        st.markdown("### 📚 Technical Notes")
        st.markdown("""
        - **Algorithm**: XGBoost Classifier (n_estimators=300, max_depth=6)
        - **Training data**: FM2023 — 22,231 players จาก 22 ลีก
        - **Features**: 20 FM attributes (scale 1–20)
        - **Target**: Best Role (34 roles, filtered to roles ≥ 30 players)
        - **Evaluation**: 5-fold Stratified Cross-Validation
        - **CV Accuracy**: 62.4% ± 0.5% (random baseline ~3%)
        - **Limitation**: FM มี role labels ที่ overlap กันสูง (Winger ↔ Inverted Winger ↔ Defensive Winger)
          ทำให้ accuracy ceiling ของ dataset นี้อยู่ต่ำกว่า 70% โดยธรรมชาติ
        """)

st.markdown("---")
st.caption("© 2025 TacticalFitAI Demo • Built with Streamlit, Plotly, and scikit-learn")
